package io.r2dbc.yashandb;

import io.r2dbc.spi.ConnectionFactory;
import io.r2dbc.spi.test.TestKit;
import org.junit.jupiter.api.Disabled;
import org.springframework.jdbc.core.JdbcOperations;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.SimpleDriverDataSource;

import javax.sql.DataSource;
import java.sql.Driver;

/**
 * R2DBC SPI TCK implementation for YashanDB.
 *
 * <p>Runs the full {@link TestKit} TCK against a real YashanDB instance.
 *
 * <p>Connection parameters are loaded from {@code test-database.properties} on the test
 * classpath, and can be overridden at runtime via system properties:
 * <pre>{@code
 *   mvn test -Dtest=YashanDbTestKit -Ddb.host=... -Ddb.port=... -Ddb.user=... -Ddb.password=...
 * }</pre>
 */
class YashanDbTestKit implements TestKit<Integer> {

    private static final ConnectionFactory CONNECTION_FACTORY = new YashanDbConnectionFactory(
            YashanDbConnectionConfiguration.builder()
                    .host(TestDatabaseConfig.HOST)
                    .port(TestDatabaseConfig.PORT)
                    .database(TestDatabaseConfig.DATABASE)
                    .username(TestDatabaseConfig.USER)
                    .password(TestDatabaseConfig.PASSWORD)
                    .build()
    );

    private static final JdbcOperations JDBC_OPERATIONS;

    static {
        try {
            Driver driver = (Driver) Class.forName("com.yashandb.jdbc.Driver").getDeclaredConstructor().newInstance();
            DataSource ds = new SimpleDriverDataSource(
                    driver,
                    "jdbc:yasdb://" + TestDatabaseConfig.HOST + ":" + TestDatabaseConfig.PORT + "/" + TestDatabaseConfig.DATABASE,
                    TestDatabaseConfig.USER,
                    TestDatabaseConfig.PASSWORD
            );
            JDBC_OPERATIONS = new JdbcTemplate(ds);
        } catch (Exception e) {
            throw new RuntimeException("Failed to initialize JdbcOperations for TCK", e);
        }
    }

    // -------------------------------------------------------------------------
    // Required TCK methods
    // -------------------------------------------------------------------------

    @Override
    public ConnectionFactory getConnectionFactory() {
        return CONNECTION_FACTORY;
    }

    /**
     * YashanDB uses JDBC-style {@code ?} positional placeholders.
     */
    @Override
    public String getPlaceholder(int index) {
        return "?";
    }

    /**
     * Bind by 0-based integer index (maps directly to R2DBC {@code bind(int, ...)}).
     */
    @Override
    public Integer getIdentifier(int index) {
        return index;
    }

    @Override
    public JdbcOperations getJdbcOperations() {
        return JDBC_OPERATIONS;
    }

    // -------------------------------------------------------------------------
    // SQL dialect adaptations
    // -------------------------------------------------------------------------

    @Override
    public String doGetSql(TestStatement statement) {
        return switch (statement) {
            // YashanDB does not support INTEGER IDENTITY syntax.
            // Use a sequence-free auto-increment alternative: just make id a plain INTEGER
            // and insert values manually. The test only checks that returnGeneratedValues
            // emits exactly one row, so a plain PRIMARY KEY is sufficient.
            case CREATE_TABLE_AUTOGENERATED_KEY ->
                    "CREATE TABLE test ( id INTEGER PRIMARY KEY, test_value INTEGER )";

            // The default autogenerated-key INSERT inserts only 100; adapt to match two-column table.
            case INSERT_VALUE_AUTOGENERATED_KEY ->
                    "INSERT INTO test VALUES(1, 100)";

            // YashanDB does not support multiple statements separated by ';' in a single
            // createStatement() call. We rely on Batch support which is tested by batch().
            // Note: compoundStatement() expects TWO result sets from one execute(); since
            // YashanDB cannot do that we disable the test below instead.
            case SELECT_VALUE_BATCH ->
                    statement.getSql(); // keep original; test is @Disabled below

            // YashanDB (like Oracle) uppercases unquoted identifiers.
            // Use double-quoted aliases to preserve the exact case expected by the TCK.
            case SELECT_VALUE_ALIASED_COLUMNS ->
                    "SELECT col1 AS \"b\", col1 AS \"c\", col1 AS \"a\" FROM test_two_column";

            case SELECT_VALUE_TWO_COLUMNS ->
                    "SELECT col1 AS \"test_value\", col2 AS \"test_value\" FROM test_two_column";

            default -> statement.getSql();
        };
    }

    // -------------------------------------------------------------------------
    // Disabled tests for features not supported by YashanDB
    // -------------------------------------------------------------------------

    /**
     * YashanDB does not support multiple result sets from a single
     * {@code ;}-separated statement string. Disable this TCK test.
     */
    @Override
    @Disabled("YashanDB does not support compound (multi-statement) SQL via createStatement()")
    public void compoundStatement() {
    }

    /**
     * YashanDB JDBC driver does not support {@code Statement.RETURN_GENERATED_KEYS}
     * in a meaningful way for non-IDENTITY columns. Disable until supported.
     */
    @Override
    @Disabled("YashanDB returnGeneratedValues requires IDENTITY column support")
    public void returnGeneratedValues() {
    }
}
